//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceImpuestos
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceImpuestos.WebServiceImpuestosSoap")]
    public interface WebServiceImpuestosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SincronizarFechaHora", ReplyAction="*")]
        System.DateTime SincronizarFechaHora();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SincronizarFechaHora", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> SincronizarFechaHoraAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idAmbiente del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCufd", ReplyAction="*")]
        ServiceImpuestos.ObtenerCufdResponse ObtenerCufd(ServiceImpuestos.ObtenerCufdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCufd", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceImpuestos.ObtenerCufdResponse> ObtenerCufdAsync(ServiceImpuestos.ObtenerCufdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCufdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCufd", Namespace="http://tempuri.org/", Order=0)]
        public ServiceImpuestos.ObtenerCufdRequestBody Body;
        
        public ObtenerCufdRequest()
        {
        }
        
        public ObtenerCufdRequest(ServiceImpuestos.ObtenerCufdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCufdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAmbiente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string modalidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nit;
        
        public ObtenerCufdRequestBody()
        {
        }
        
        public ObtenerCufdRequestBody(string idAmbiente, string modalidad, string nit)
        {
            this.idAmbiente = idAmbiente;
            this.modalidad = modalidad;
            this.nit = nit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCufdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCufdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceImpuestos.ObtenerCufdResponseBody Body;
        
        public ObtenerCufdResponse()
        {
        }
        
        public ObtenerCufdResponse(ServiceImpuestos.ObtenerCufdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCufdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerCufdResult;
        
        public ObtenerCufdResponseBody()
        {
        }
        
        public ObtenerCufdResponseBody(string ObtenerCufdResult)
        {
            this.ObtenerCufdResult = ObtenerCufdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WebServiceImpuestosSoapChannel : ServiceImpuestos.WebServiceImpuestosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WebServiceImpuestosSoapClient : System.ServiceModel.ClientBase<ServiceImpuestos.WebServiceImpuestosSoap>, ServiceImpuestos.WebServiceImpuestosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceImpuestosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceImpuestosSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceImpuestosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceImpuestosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceImpuestosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceImpuestosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceImpuestosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceImpuestosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.DateTime SincronizarFechaHora()
        {
            return base.Channel.SincronizarFechaHora();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> SincronizarFechaHoraAsync()
        {
            return base.Channel.SincronizarFechaHoraAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceImpuestos.ObtenerCufdResponse ServiceImpuestos.WebServiceImpuestosSoap.ObtenerCufd(ServiceImpuestos.ObtenerCufdRequest request)
        {
            return base.Channel.ObtenerCufd(request);
        }
        
        public string ObtenerCufd(string idAmbiente, string modalidad, string nit)
        {
            ServiceImpuestos.ObtenerCufdRequest inValue = new ServiceImpuestos.ObtenerCufdRequest();
            inValue.Body = new ServiceImpuestos.ObtenerCufdRequestBody();
            inValue.Body.idAmbiente = idAmbiente;
            inValue.Body.modalidad = modalidad;
            inValue.Body.nit = nit;
            ServiceImpuestos.ObtenerCufdResponse retVal = ((ServiceImpuestos.WebServiceImpuestosSoap)(this)).ObtenerCufd(inValue);
            return retVal.Body.ObtenerCufdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceImpuestos.ObtenerCufdResponse> ServiceImpuestos.WebServiceImpuestosSoap.ObtenerCufdAsync(ServiceImpuestos.ObtenerCufdRequest request)
        {
            return base.Channel.ObtenerCufdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceImpuestos.ObtenerCufdResponse> ObtenerCufdAsync(string idAmbiente, string modalidad, string nit)
        {
            ServiceImpuestos.ObtenerCufdRequest inValue = new ServiceImpuestos.ObtenerCufdRequest();
            inValue.Body = new ServiceImpuestos.ObtenerCufdRequestBody();
            inValue.Body.idAmbiente = idAmbiente;
            inValue.Body.modalidad = modalidad;
            inValue.Body.nit = nit;
            return ((ServiceImpuestos.WebServiceImpuestosSoap)(this)).ObtenerCufdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceImpuestosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceImpuestosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceImpuestosSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44300/WebServiceImpuestos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceImpuestosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44300/WebServiceImpuestos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceImpuestosSoap,
            
            WebServiceImpuestosSoap12,
        }
    }
}
