//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBNB
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBNB.ServiceBNBSoap")]
    public interface ServiceBNBSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Ncuenta del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarSaldo", ReplyAction="*")]
        ServiceBNB.ConsultarSaldoResponse ConsultarSaldo(ServiceBNB.ConsultarSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarSaldo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceBNB.ConsultarSaldoResponse> ConsultarSaldoAsync(ServiceBNB.ConsultarSaldoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarSaldoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarSaldo", Namespace="http://tempuri.org/", Order=0)]
        public ServiceBNB.ConsultarSaldoRequestBody Body;
        
        public ConsultarSaldoRequest()
        {
        }
        
        public ConsultarSaldoRequest(ServiceBNB.ConsultarSaldoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarSaldoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ncuenta;
        
        public ConsultarSaldoRequestBody()
        {
        }
        
        public ConsultarSaldoRequestBody(string Ncuenta)
        {
            this.Ncuenta = Ncuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarSaldoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarSaldoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceBNB.ConsultarSaldoResponseBody Body;
        
        public ConsultarSaldoResponse()
        {
        }
        
        public ConsultarSaldoResponse(ServiceBNB.ConsultarSaldoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarSaldoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double ConsultarSaldoResult;
        
        public ConsultarSaldoResponseBody()
        {
        }
        
        public ConsultarSaldoResponseBody(double ConsultarSaldoResult)
        {
            this.ConsultarSaldoResult = ConsultarSaldoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServiceBNBSoapChannel : ServiceBNB.ServiceBNBSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceBNBSoapClient : System.ServiceModel.ClientBase<ServiceBNB.ServiceBNBSoap>, ServiceBNB.ServiceBNBSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceBNBSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceBNBSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceBNBSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBNBSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceBNBSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBNBSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceBNBSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBNBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceBNB.ConsultarSaldoResponse ServiceBNB.ServiceBNBSoap.ConsultarSaldo(ServiceBNB.ConsultarSaldoRequest request)
        {
            return base.Channel.ConsultarSaldo(request);
        }
        
        public double ConsultarSaldo(string Ncuenta)
        {
            ServiceBNB.ConsultarSaldoRequest inValue = new ServiceBNB.ConsultarSaldoRequest();
            inValue.Body = new ServiceBNB.ConsultarSaldoRequestBody();
            inValue.Body.Ncuenta = Ncuenta;
            ServiceBNB.ConsultarSaldoResponse retVal = ((ServiceBNB.ServiceBNBSoap)(this)).ConsultarSaldo(inValue);
            return retVal.Body.ConsultarSaldoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceBNB.ConsultarSaldoResponse> ServiceBNB.ServiceBNBSoap.ConsultarSaldoAsync(ServiceBNB.ConsultarSaldoRequest request)
        {
            return base.Channel.ConsultarSaldoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceBNB.ConsultarSaldoResponse> ConsultarSaldoAsync(string Ncuenta)
        {
            ServiceBNB.ConsultarSaldoRequest inValue = new ServiceBNB.ConsultarSaldoRequest();
            inValue.Body = new ServiceBNB.ConsultarSaldoRequestBody();
            inValue.Body.Ncuenta = Ncuenta;
            return ((ServiceBNB.ServiceBNBSoap)(this)).ConsultarSaldoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceBNBSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceBNBSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceBNBSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44322/ServiceBNB.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceBNBSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44322/ServiceBNB.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceBNBSoap,
            
            ServiceBNBSoap12,
        }
    }
}
