//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConversionMoneda
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConversionMoneda.WebServiceBancoSoap")]
    public interface WebServiceBancoSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento moneda del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtnercotizacion", ReplyAction="*")]
        ConversionMoneda.ObtnercotizacionResponse Obtnercotizacion(ConversionMoneda.ObtnercotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtnercotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ConversionMoneda.ObtnercotizacionResponse> ObtnercotizacionAsync(ConversionMoneda.ObtnercotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtnercotizacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Obtnercotizacion", Namespace="http://tempuri.org/", Order=0)]
        public ConversionMoneda.ObtnercotizacionRequestBody Body;
        
        public ObtnercotizacionRequest()
        {
        }
        
        public ObtnercotizacionRequest(ConversionMoneda.ObtnercotizacionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtnercotizacionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string moneda;
        
        public ObtnercotizacionRequestBody()
        {
        }
        
        public ObtnercotizacionRequestBody(string moneda)
        {
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtnercotizacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtnercotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConversionMoneda.ObtnercotizacionResponseBody Body;
        
        public ObtnercotizacionResponse()
        {
        }
        
        public ObtnercotizacionResponse(ConversionMoneda.ObtnercotizacionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtnercotizacionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal ObtnercotizacionResult;
        
        public ObtnercotizacionResponseBody()
        {
        }
        
        public ObtnercotizacionResponseBody(decimal ObtnercotizacionResult)
        {
            this.ObtnercotizacionResult = ObtnercotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WebServiceBancoSoapChannel : ConversionMoneda.WebServiceBancoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WebServiceBancoSoapClient : System.ServiceModel.ClientBase<ConversionMoneda.WebServiceBancoSoap>, ConversionMoneda.WebServiceBancoSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceBancoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceBancoSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceBancoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceBancoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceBancoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceBancoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceBancoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceBancoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConversionMoneda.ObtnercotizacionResponse ConversionMoneda.WebServiceBancoSoap.Obtnercotizacion(ConversionMoneda.ObtnercotizacionRequest request)
        {
            return base.Channel.Obtnercotizacion(request);
        }
        
        public decimal Obtnercotizacion(string moneda)
        {
            ConversionMoneda.ObtnercotizacionRequest inValue = new ConversionMoneda.ObtnercotizacionRequest();
            inValue.Body = new ConversionMoneda.ObtnercotizacionRequestBody();
            inValue.Body.moneda = moneda;
            ConversionMoneda.ObtnercotizacionResponse retVal = ((ConversionMoneda.WebServiceBancoSoap)(this)).Obtnercotizacion(inValue);
            return retVal.Body.ObtnercotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConversionMoneda.ObtnercotizacionResponse> ConversionMoneda.WebServiceBancoSoap.ObtnercotizacionAsync(ConversionMoneda.ObtnercotizacionRequest request)
        {
            return base.Channel.ObtnercotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConversionMoneda.ObtnercotizacionResponse> ObtnercotizacionAsync(string moneda)
        {
            ConversionMoneda.ObtnercotizacionRequest inValue = new ConversionMoneda.ObtnercotizacionRequest();
            inValue.Body = new ConversionMoneda.ObtnercotizacionRequestBody();
            inValue.Body.moneda = moneda;
            return ((ConversionMoneda.WebServiceBancoSoap)(this)).ObtnercotizacionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceBancoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceBancoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceBancoSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44300/WebServiceBanco.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceBancoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44300/WebServiceBanco.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceBancoSoap,
            
            WebServiceBancoSoap12,
        }
    }
}
